version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: typ-engineer-front
    volumes:
      - ".:/src"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
